version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  test:
    executor:
      name: android/android-machine

    steps:
      - checkout

      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue
          working_directory: mobile

      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-25;google_apis;x86
          working_directory: mobile
  
  build:
    executor:
      name: android/android-machine

    steps:
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease
          working_directory: mobile

workflows:
  ci:
    jobs:
      - test
#      - build
