[versions]
# libraries
## jetpack
core = "1.9.0"
activity = "1.7.2"
lifecycle = "2.6.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
### jetpack.compose
compose-bom = "2023.09.02"

## junit
junit = "4.13.2"

## firebase
firebase-bom = "32.3.1"

# plugins
agp = "8.1.1"
kotlin = "1.9.0"


[libraries]
# jetpack
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
## jetpack.compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
### jetpack.compose.ui
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
### jetpack.compose.material3
material3 = { group = "androidx.compose.material3", name = "material3" }

# junit
junit = { group = "junit", name = "junit", version.ref = "junit" }

# firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }


[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }


[bundles]

